name: Build from fork

on:
  pull_request_target:
    types:
      - ready_for_review
    paths:
      - '**'
      - '!.github/'

concurrency:
  group: ${{ github.head_ref || github.ref }}

jobs:
  deb:
    name: 'DEB'
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        os:
          - debian
        version:
          - bookworm
          - bullseye
          - buster
        platform:
          - name: amd64
            runner: ubuntu-latest
          - name: arm32v7
            runner: linux-arm64-4-core-public
          - name: arm64v8
            runner: linux-arm64-4-core-public
        exclude:
          - version: bookworm
            platform:
              name: amd64
          - version: bookworm
            platform:
              name: arm64v8
          - version: bullseye

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: code

      - name: Checkout reusable actions
        uses: actions/checkout@v4
        with:
          repository: signalwire/actions-template
          ref: main
          fetch-depth: 1
          path: actions
          sparse-checkout: |
            .github/actions/docker-build-artifacts/action.yml
          sparse-checkout-cone-mode: false

      - name: Build artifacts via Docker
        uses: ./actions/.github/actions/docker-build-artifacts
        with:
          REPO_DOMAIN: freeswitch.signalwire.com
          PLATFORM: ${{ matrix.platform.name }}
          DOCKERFILE: .github/docker/${{ matrix.os }}/${{ matrix.version }}/${{ matrix.platform.name }}/Dockerfile
          MAINTAINER: 'Andrey Volk <andrey@signalwire.com>'
          WORKING_DIRECTORY: code
        env:
          REPO_USERNAME: 'SWUSERNAME'
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
